services:
  - type: web
    name: media-center
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: media-center-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: media-center-db
    databaseName: media_center
    user: admin